# Generated by Django 4.0.5 on 2022-07-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/sliders/')),
                ('url', models.URLField()),
                ('is_show', models.BooleanField(default=False)),
            ],
        ),
    ]
