# Generated by Django 4.0.5 on 2022-07-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-title'], 'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدر ها'},
        ),
        migrations.AddField(
            model_name='slider',
            name='fade_image',
            field=models.ImageField(default=3, upload_to='', verbose_name='عکس فدی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.CharField(max_length=200, verbose_name='توضیحات اسلایدر'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='images/sliders/', verbose_name='تصویر اسلایدر'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='نمایش داده شود؟'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=110, verbose_name='عنوان اسلایدر'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.URLField(verbose_name='آدرس اسلایدر'),
        ),
    ]
