# Generated by Django 4.0.5 on 2022-07-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sliders', '0002_alter_slider_options_slider_fade_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='fade_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس فدی'),
        ),
    ]
