# Generated by Django 4.0.5 on 2022-07-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sliders', '0003_alter_slider_fade_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='fade_image',
        ),
        migrations.AddField(
            model_name='slider',
            name='fade_up_image',
            field=models.ImageField(default='image.png', upload_to='images/sliders/fades/', verbose_name='تصویر متحرک'),
        ),
    ]
