# Generated by Django 4.0.5 on 2022-07-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sliders', '0004_remove_slider_fade_image_slider_fade_up_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-title', 'is_show'], 'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدر ها'},
        ),
    ]
