# Generated by Django 4.0.5 on 2022-07-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل مجموعه')),
                ('copy_right_text', models.CharField(max_length=120, verbose_name='متن کپی رایت')),
                ('address', models.CharField(max_length=400, verbose_name='آدرس مجموعه')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس مجموعه')),
            ],
            options={
                'verbose_name': 'تنظیمات وبسایت ',
                'verbose_name_plural': 'تنظیمات وبسایت',
            },
        ),
    ]
