# Generated by Django 4.0.5 on 2022-07-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان شبکه اجتماعی ')),
                ('url', models.URLField(verbose_name='آدرس شبکه اجتماعی')),
                ('icon', models.CharField(max_length=15, verbose_name='آیکون شبکه اجتماعی ')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
    ]
