# Generated by Django 4.0.5 on 2022-07-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0003_alter_socialmedia_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='map_address',
            field=models.URLField(blank=True, verbose_name='آدرس مجموعه در گوگل مپ'),
        ),
    ]
