# Generated by Django 4.0.5 on 2022-07-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0004_setting_map_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='map_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='آدرس مجموعه در گوگل مپ'),
        ),
    ]
