# Generated by Django 4.0.5 on 2022-08-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان مقاله'),
        ),
    ]
