# Generated by Django 4.0.5 on 2022-07-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110, verbose_name='نام کاربر')),
                ('subject', models.CharField(max_length=150, verbose_name='عنوان پیام کاربر')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل کاربر')),
                ('text', models.TextField(verbose_name='پیفام کاربر')),
            ],
            options={
                'verbose_name': 'پیفام کاربر',
                'verbose_name_plural': 'پیغام های کاربران',
            },
        ),
    ]
