# Generated by Django 4.0.5 on 2022-07-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='text',
            field=models.TextField(max_length=500, verbose_name='پیفام کاربر'),
        ),
    ]
