# Generated by Django 4.0.5 on 2022-07-20 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0005_alter_skill_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='percent',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100, 'مقدار وارد شده صحیح نیست بیشتر از حد مجاز است '), django.core.validators.MinValueValidator(0, 'مقدار وارد شده صیحی نیست و از حد مجاز کمتر است')], verbose_name='درصد تسلط بر مهارت'),
        ),
    ]
