# Generated by Django 4.0.5 on 2022-07-20 21:50

import Resume.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0006_alter_skill_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='percent',
            field=models.IntegerField(validators=[Resume.validators.max_value_validator, django.core.validators.MinValueValidator(0, 'مقدار وارد شده صیحی نیست و از حد مجاز کمتر است')], verbose_name='درصد تسلط بر مهارت'),
        ),
    ]
