# Generated by Django 4.0.5 on 2022-07-20 22:20

import Resume.validators
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0007_alter_skill_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='توضیح بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percent',
            field=models.IntegerField(validators=[Resume.validators.max_value_validator, Resume.validators.min_value_validator], verbose_name='درصد تسلط بر مهارت'),
        ),
    ]
