# Generated by Django 4.0.5 on 2022-07-20 22:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0009_alter_biography_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='توضیح بیوگرافی'),
        ),
    ]
