# Generated by Django 4.0.5 on 2022-07-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0010_alter_biography_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_count', models.IntegerField(verbose_name='تعداد پروژه های موفق')),
                ('working_hours', models.IntegerField(verbose_name='تعداد ساعات کار')),
                ('rats', models.IntegerField(verbose_name='تعداد امتیاز های کاربران')),
                ('customers', models.IntegerField(verbose_name='تعداد مشتری های شما')),
            ],
            options={
                'verbose_name': 'تجربه',
                'verbose_name_plural': 'تجربه ها',
            },
        ),
    ]
