# Generated by Django 4.0.5 on 2022-07-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0011_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='rats',
            new_name='rates',
        ),
    ]
