# Generated by Django 4.0.5 on 2022-07-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0012_rename_rats_experience_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='عنوان نمونه کار')),
                ('image', models.ImageField(upload_to='images/Resume/portfolio/', verbose_name='تصویر نمونه کار')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کار ها',
                'ordering': ('-title',),
            },
        ),
    ]
