# Generated by Django 4.0.5 on 2022-07-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0013_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='عنوان دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی  ها',
                'ordering': ('-title',),
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='categories',
            field=models.ManyToManyField(to='Resume.categoryportfolio', verbose_name='دسته بندی'),
        ),
    ]
